---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler


install:
  - bash ./tests/ansible-setup.sh
  - bundle install

script:
    - ansible --version
    - export TRAVIS=True
    - bundle exec kitchen test

after_success:
    - echo "Success"