---
# https://github.com/cloudfoundry-incubator/garden-linux/

- name: garden_linux | Install Exta linux kernel
  apt: 
    name="linux-image-extra-{{ ansible_kernel }}"
    state=present

- name: garden_linux | Load aufs
  modprobe:
    name="aufs"

- name: common | Ensure Concourse garden directory exists
  file: 
    path="{{ item }}"
    state="directory"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"
    mode="0750"
  with_items:
    - /opt/garden/depot 
    - /opt/garden/graph 
    - /opt/garden/state

- name: garden_linux | Check for binary
  stat: 
    path="{{ concourseci_garden_dir }}/src/github.com/cloudfoundry-incubator/garden-linux/"
  register: st

- name: garden_linux | Git clone Garden Linux
  git: 
    repo="https://github.com/cloudfoundry-incubator/garden-linux-release"
    dest="{{ concourseci_garden_dir }}"
    version="{{ concourseci_garden_version }}"
    recursive=yes
    update=no
  register: reg_garden_linux
  become_user: "{{ concourseci_user }}"
  when: not st.stat.exists or concourseci_garden_update_force

- name: garden_linux | Build Garden Linux
  shell: /usr/bin/make
  args:
    chdir: "{{ concourseci_garden_dir }}/src/github.com/cloudfoundry-incubator/garden-linux/"
    executable: "/bin/bash"
  environment:
    GOPATH: "{{ concourseci_garden_dir }}"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin://usr/local/go/bin/"
  become_user: "{{ concourseci_user }}"
  when: reg_garden_linux | changed

