---

- name: Kernel upgrade
  include: kernel_update.yml
  when: "{{ ansible_os_family == 'Linux' }}"

- name: Common tasks
  include: common_nix.yml
  when: "{{ ansible_os_family == 'Linux' or  ansible_os_family == 'Darwin' }}"

- name: Install tasks
  include: install_nix.yml
  when: "{{ ansible_os_family == 'Linux' or  ansible_os_family == 'Darwin' }}"

- name: Manage web node
  include: web_nix.yml
  when: "{{ groups[concourseci_web_group] is defined and inventory_hostname in groups[concourseci_web_group] and ansible_os_family == 'Linux' or  ansible_os_family == 'Darwin' }}"

- name: Manage worker node
  include: worker_nix.yml
  when: "{{ groups[concourseci_worker_group] is defined and inventory_hostname in groups[concourseci_worker_group] and ansible_os_family == 'Linux' or  ansible_os_family == 'Darwin'  }}"
