---

- name: Install | Concourse web start script
  template:
    src="concourse-web.j2"
    dest="{{ concourseci_bin_dir }}/concourse-web"
    mode=0755

- name: Install | Concourse web start init script
  template:
    src="concourse-web-init.sh.j2"
    dest="/etc/init.d/concourse-web"
    mode=0755
