---

- name: Install | Concourse web start script
  template:
    src="concourse-web.j2"
    dest="{{ concourseci_bin_dir }}/concourse-web"
    mode=0755
  notify:
   - restart concourse-web

- name: Install | Concourse web start init script
  template:
    src="concourse-web-init.sh.j2"
    dest="/etc/init.d/concourse-web"
    mode=0755
  notify:
   - restart concourse-web

- name: Install | Ensure Concourse web is running and Starts on boot
  service:
    name="concourse-web"
    state="started"
    enabled=True