---

- name: web | Copy session key 
  copy:
    content="{{ item.content }}"
    dest="{{ item.dest }}"
    mode="{{ item.mode }}"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"
  with_items: 
    - content: "{{ concourseci_session_signing_key.private }}"
      dest: "{{ concourseci_session_signing_key.file }}"
      mode: "0600"
    - content: "{{ concourseci_session_signing_key.public }}"
      dest: "{{ concourseci_session_signing_key.file }}.pub"
      mode: "0644"

- name: web | Copy host key
  copy:
    content="{{ item.content }}"
    dest="{{ item.dest }}"
    mode="{{ item.mode }}"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"
  with_items: 
    - content: "{{ concourseci_host_key.private }}"
      dest: "{{ concourseci_host_key.file }}"
      mode: "0600"
    - content: "{{ concourseci_host_key.public }}"
      dest: "{{ concourseci_host_key.file }}.pub"
      mode: "0644"

- name: web | Copy worker key
  copy:
    content="{{ item.content }}"
    dest="{{ item.dest }}"
    mode="{{ item.mode }}"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"
  with_items: 
    - content: "{{ concourseci_worker_key[0].private }}"
      dest: "{{ concourseci_worker_key[0].file }}"
      mode: "0600"
    - content: "{{ concourseci_worker_key[0].public }}"
      dest: "{{ concourseci_worker_key[0].file }}.pub"
      mode: "0644"

- name: web | Concourse web start script
  template:
    src="concourse-web.j2"
    dest="{{ concourseci_bin_dir }}/concourse-web"
    mode=0755
  notify:
   - restart concourse-web

- name: web | Concourse web start init script
  template:
    src="concourse-web-init.sh.j2"
    dest="/etc/init.d/concourse-web"
    mode=0755
  notify:
   - restart concourse-web

- name: web | Ensure Concourse web is running and Starts on boot
  service:
    name="concourse-web"
    state="started"
    enabled=True