---

- name: worker | Concourse worker start script
  template:
    src="concourse-worker.j2"
    dest="{{ concourseci_bin_dir }}/concourse-worker"
    mode=0755
  notify:
   - restart concourse-worker

- name: worker | Copy session public key
  copy:
    content="{{ concourseci_key_session_public }}"
    dest="{{ CONCOURSE_WEB_SESSION_SIGNING_KEY }}.pub"
    mode="0644"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"
  notify:
   - restart concourse-worker

- name: worker | Copy tsa public key
  copy:
    content="{{ concourseci_key_tsa_public }}"
    dest="{{ CONCOURSE_WEB_TSA_HOST_KEY }}.pub"
    mode="0644"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"
  notify:
   - restart concourse-worker

- name: worker | Copy worker public key
  copy:
    content="{{ concourseci_key_worker_public }}"
    dest="{{ CONCOURSE_WORKER_TSA_WORKER_PRIVATE_KEY }}.pub"
    mode="0644"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"

- name: worker | Copy worker private key
  copy:
    content="{{ concourseci_key_worker_private }}"
    dest="{{ CONCOURSE_WORKER_TSA_WORKER_PRIVATE_KEY }}"
    mode="0600"
    owner="{{ concourseci_user }}"
    group="{{ concourseci_group }}"
  no_log: True
  notify:
    - restart concourse-worker

- name: Worker | Concourse worker start script
  template:
    src="concourse-worker.j2"
    dest="{{ concourseci_bin_dir }}/concourse-worker"
    mode=0755
  notify:
   - restart concourse-worker

- name: Worker | Concourse worker start init script
  template:
    src="concourse-worker-init.sh.j2"
    dest="/etc/init.d/concourse-worker"
    mode=0755
  notify:
   - restart concourse-worker
  when: "{{ ansible_system == 'Linux' }}"

- name: Worker | Ensure Concourse worker is running and Starts on boot
  service:
    name="concourse-worker"
    state="started"
    enabled=True
  ignore_errors: "{{ concourse_ignore_errors }}"
