---

- name: Install | Concourse worker start script
  template:
    src="concourse-worker.j2"
    dest="{{ concourseci_bin_dir }}/concourse-worker"
    mode=0755

- name: Install | Concourse worker start init script
  template:
    src="concourse-worker-init.sh.j2"
    dest="/etc/init.d/concourse-worker"
    mode=0755
